Repository aenix-io/etcd-operator, pull requests merged in 2024-06, with the labels that each got.

#229 [222] Add autocomaction to ConfigMap
  internal/controller/factory/statefulset.go
Labels: feature, controllers

#227 update logging
  Dockerfile
  cmd/app/commandline.go
  cmd/main.go
  go.mod
  go.sum
  internal/controller/etcdcluster_controller.go
  internal/controller/etcdcluster_controller_test.go
  internal/controller/factory/builders.go
  internal/controller/factory/configMap.go
  internal/controller/factory/configmap_test.go
  internal/controller/factory/pdb.go
  internal/controller/factory/pdb_test.go
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
  internal/controller/factory/suite_test.go
  internal/controller/factory/svc.go
  internal/controller/factory/svc_test.go
  internal/controller/suite_test.go
  internal/log/logger.go
  internal/signal/signal.go
Labels: chore, controllers

#230 [102] Slightly update default template and add some comments
  charts/etcd-operator/README.md
  charts/etcd-operator/README.md.gotmpl
  charts/etcd-operator/values.schema.json
  charts/etcd-operator/values.yaml
Labels: documentation, feature

#233 [232] Create kind with accurate kubernetes version
  .github/workflows/make-test-e2e.yaml
  .github/workflows/make-test.yaml
  Makefile
Labels: feature

#204 add auth enabler
  .gitignore
  Makefile
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/etcdcluster_types_test.go
  api/v1alpha1/etcdcluster_webhook.go
  api/v1alpha1/etcdcluster_webhook_test.go
  charts/etcd-operator/crds/etcd-cluster.yaml
  charts/etcd-operator/templates/workload/deployment.yml
  config/crd/bases/etcd.aenix.io_etcdclusters.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  examples/manifests/etcdcluster-with-external-certificates.yaml
  internal/controller/etcdcluster_controller.go
  internal/controller/etcdcluster_controller_test.go
  internal/controller/factory/statefulset.go
  site/content/en/docs/v0.2/reference/api.md
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: documentation, feature, controllers, api-change

#240 run kind for e2e tests with kube-proxy in ipvs mode
  Makefile
  test/e2e/config.yaml
Labels: chore

#234 Add volumeClaimTemplates only if storage.EmptyDir is nil
  .golangci.yml
  examples/manifests/etcdcluster-emptydir.yaml
  internal/controller/factory/statefulset.go
  test/e2e/e2e_test.go
Labels: bugfix, controllers

#242 set cosign-installer to use default (latest) cosign version
  .github/workflows/docker-publish.yaml
Labels: bugfix

#207 Extended status check for reconciliation
  api/v1alpha1/etcdcluster_types.go
  config/rbac/role.yaml
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/etcd_client.go
  internal/controller/observables.go
  test/e2e/e2e_test.go
Labels: controllers, api-change
