Repository aenix-io/etcd-operator, pull requests merged in 2024-04, with the labels that each got.

#95 enh: Add common commands for local development
  Makefile
Labels: enhancement

#101 Evolve Makefile, improve developer experience, update documentation
  .github/workflows/make-test-e2e.yaml
  HOW-TO-START-DEVELOPMENT.md
  Makefile
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: enhancement

#93 Add PDB to EtcdCluster spec and implement validation webhhoks
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/etcdcluster_types_test.go
  api/v1alpha1/etcdcluster_webhook.go
  api/v1alpha1/etcdcluster_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/etcd.aenix.io_etcdclusters.yaml
  config/rbac/role.yaml
  config/samples/etcd.aenix.io_v1alpha1_etcdcluster.yaml
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/builders.go
  internal/controller/factory/pdb.go
  internal/controller/factory/pdb_test.go
Labels: feature

#99 Feature/77 validate extraargs
  api/v1alpha1/etcdcluster_webhook.go
  config/samples/etcd.aenix.io_v1alpha1_etcdcluster.yaml
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
Labels: ok-to-test, feature

#78 [50] Helm-chart initial commit
  .github/workflows/helm-publish.yaml
  .pre-commit-config.yaml
  Makefile
  charts/etcd-operator/.helmignore
  charts/etcd-operator/Chart.yaml
  charts/etcd-operator/README.md
  charts/etcd-operator/crds/etcd-cluster.yaml
  charts/etcd-operator/templates/_helpers.tpl
  charts/etcd-operator/templates/cert-manager/certificate.yml
  charts/etcd-operator/templates/cert-manager/issuer.yml
  charts/etcd-operator/templates/cert-manager/mutatingwebhookconfiguration.yml
  charts/etcd-operator/templates/cert-manager/validatingwebhookconfiguration.yml
  charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
  charts/etcd-operator/templates/rbac/clusterrole-metrics-reader.yml
  charts/etcd-operator/templates/rbac/clusterrole-proxy-role.yml
  charts/etcd-operator/templates/rbac/clusterrolebinding-manager-rolebinding.yml
  charts/etcd-operator/templates/rbac/clusterrolebinding-proxy-rolebinding.yml
  charts/etcd-operator/templates/rbac/role-leader-election-role.yml
  charts/etcd-operator/templates/rbac/rolebinding-leader-election-rolebinding.yml
  charts/etcd-operator/templates/workload/configmap-env.yaml
  charts/etcd-operator/templates/workload/deployment.yml
  charts/etcd-operator/templates/workload/service-controller-manager-metrics-service.yml
  charts/etcd-operator/templates/workload/service-webhook-service.yml
  charts/etcd-operator/templates/workload/serviceaccount.yml
  charts/etcd-operator/values.schema.json
  charts/etcd-operator/values.yaml
Labels: feature

#118 Rename CRD fields
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/etcdcluster_webhook.go
  api/v1alpha1/etcdcluster_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd-operator/crds/etcd-cluster.yaml
  config/crd/bases/etcd.aenix.io_etcdclusters.yaml
  config/crd/kustomization.yaml
  config/samples/etcd.aenix.io_v1alpha1_etcdcluster.yaml
  internal/controller/factory/pdb.go
  internal/controller/factory/pdb_test.go
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
Labels: feature

#121 Enhancement/usd std slice index func
  internal/controller/factory/statefulset.go
Labels: enhancement, ok-to-test

#122 Fix/ full example manifest
  examples/manifests/etcdcluster-full.yaml
Labels: enhancement

#129 Simplify the condition transition rules
  internal/controller/etcdcluster_controller.go
Labels: enhancement

#125 Implement mounting user certificates and keys
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/etcdcluster_webhook.go
  api/v1alpha1/etcdcluster_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd-operator/crds/etcd-cluster.yaml
  config/crd/bases/etcd.aenix.io_etcdclusters.yaml
  config/manager/kustomization.yaml
  examples/manifests/etcdcluster-with-external-certificates.yaml
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
Labels: feature

#128 add pull_request_target as release-drafter workflow trigger
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#170 Fix double import core/v1 pkg for sts test file
  internal/controller/factory/statefulset_test.go
Labels: enhancement, ok-to-test

#173 [161] Add plain manifests to release process
  .github/workflows/helm-publish.yaml
  .github/workflows/release-assets.yaml
  .gitignore
  Makefile
  site/content/en/docs/v0.1/quickstart.md
Labels: documentation, ok-to-test, feature

#179 add logging
  internal/controller/factory/builders.go
  internal/controller/factory/configMap.go
  internal/controller/factory/pdb.go
  internal/controller/factory/statefulset.go
  internal/controller/factory/svc.go
Labels: chore

#182 update tests
  internal/controller/etcdcluster_controller_test.go
  internal/controller/factory/condition_test.go
  internal/controller/factory/configmap_test.go
  internal/controller/factory/pdb_test.go
  internal/controller/factory/statefulset_test.go
  internal/controller/factory/suite_test.go
  internal/controller/factory/svc_test.go
  internal/controller/suite_test.go
Labels: chore

#184 Add nilaway linter.
  .pre-commit-config.yaml
  Makefile
  internal/controller/etcdcluster_controller.go
Labels: ok-to-test

#124 Feat/implement service spec
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd-operator/crds/etcd-cluster.yaml
  config/crd/bases/etcd.aenix.io_etcdclusters.yaml
  examples/manifests/etcdcluster-kamaji.yaml
  examples/manifests/etcdcluster-with-external-certificates.yaml
  internal/controller/etcdcluster_controller.go
  internal/controller/etcdcluster_controller_test.go
  internal/controller/factory/builders.go
  internal/controller/factory/configMap.go
  internal/controller/factory/statefulset.go
  internal/controller/factory/svc.go
  internal/controller/factory/svc_test.go
  internal/k8sutils/strategicmerge.go
  test/e2e/e2e_test.go
Labels: feature

#193 add aobort as reviewer
  OWNERS
Labels: chore

#194 fix: download link on getting started page
  site/content/en/docs/v0.2/getting-started/_index.md
Labels: documentation

#198 update codebase
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/builders.go
  internal/controller/factory/configMap.go
  internal/controller/factory/configmap_test.go
  internal/controller/factory/pdb.go
  internal/controller/factory/pdb_test.go
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
  internal/controller/factory/suite_test.go
  internal/controller/factory/svc.go
  internal/controller/factory/svc_test.go
Labels: chore, controllers
