Repository aenix-io/etcd-operator, pull requests merged in 2024-05, with the labels that each got.

#213 doc: add examples link
  site/content/en/docs/v0.2/examples/_index.md
Labels: documentation

#219 Add aobort as a codeowner next to AlexGluck
  CODEOWNERS
Labels: feature

#218 Use the latest version in matrix as a default from Makefile
  .github/workflows/make-test-e2e.yaml
  .github/workflows/make-test.yaml
  Makefile
Labels: bugfix

#197 feat: Generate CRD docs
  .crd-docs.yaml
  .pre-commit-config.yaml
  Makefile
  site/content/en/docs/v0.2/reference/_index.md
  site/content/en/docs/v0.2/reference/api.md
  site/reference-templates/gv_detail.tpl
  site/reference-templates/gv_list.tpl
  site/reference-templates/type.tpl
  site/reference-templates/type_members.tpl
Labels: documentation

#217 feat: set quota-backend-bytes to 95% of requested size
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
Labels: ok-to-test, feature, controllers
