Repository aenix-io/etcd-operator, pull requests merged in 2024-08, with the labels that each got.

#258 Add watch verb for storageclasses rbac
  charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
  config/rbac/role.yaml
  internal/controller/etcdcluster_controller.go
Labels: ok-to-test, controllers

#252 Add a helper set library to facilitate implementation of the new health check procedure
  pkg/set/set.go
Labels: documentation, controllers

#262 Add @lllamnyp to codeowners of some sections
  CODEOWNERS
Labels: chore
