Repository aenix-io/etcd-operator, pull requests merged in 2024-12, with the labels that each got.

#275 update CODEOWNERS
  CODEOWNERS
Labels: chore

#181 Create a design-document for the controller
  docs/DESIGN.md
  docs/sts-flow.svg
Labels: documentation

#276 wip: controller flow
  go.mod
  go.sum
  internal/controller/etcdcluster_controller.go
  internal/controller/etcdcluster_controller_new.go
  internal/controller/observables.go
  site/content/en/docs/v0.4/reference/api.md
Labels: documentation, controllers

#278 Implement TemplateStatefulSet function
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
Labels: documentation, controllers
