Repository aenix-io/etcd-operator, pull requests merged in 2024-03, with the labels that each got.

#26 Implementation of Ready status condition
  api/v1alpha1/etcdcluster_types.go
  internal/controller/etcdcluster_controller.go
  internal/controller/etcdcluster_controller_test.go
Labels: ok-to-test

#44 feat: Create ClusterIP Service for clients access to cluster
  internal/controller/etcdcluster_controller.go
  internal/controller/etcdcluster_controller_test.go
Labels: ok-to-test

#38 CI workflow for docs website
  .github/workflows/hugo.yaml
Labels: documentation

#41 enh: Update status in reconcile loop, not in defer
  internal/controller/etcdcluster_controller.go
Labels: enhancement, ok-to-test

#59 replace go-install-tool with go install
  CODEOWNERS
  Makefile
Labels: ok-to-test

#63 Add image field to EtcdCluster spec
  api/.gitkeep
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/etcdcluster_webhook.go
  api/v1alpha1/etcdcluster_webhook_test.go
  config/crd/bases/etcd.aenix.io_etcdclusters.yaml
  internal/controller/factory/statefulset.go
Labels: feature

#89 Reuse common labels
  internal/controller/factory/labels_builder.go
  internal/controller/factory/labels_builder_test.go
  internal/controller/factory/statefulset.go
  internal/controller/factory/svc.go
Labels: ok-to-test

#96 Fix load docker image doc
  HOW-TO-START-DEVELOPMENT.md
Labels: documentation

#91 feat: Add quickstart page
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  site/content/en/docs/v0.1/quickstart.md
  site/docker-compose.yaml
Labels: documentation

#94 fix: use status condition for setting cluster configmap state
  api/v1alpha1/etcdcluster_types.go
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/condition.go
  internal/controller/factory/condition_test.go
  internal/controller/factory/configMap.go
  internal/controller/factory/configmap_test.go
Labels: bugfix
