Repository aenix-io/etcd-operator, pull requests merged in 2024-07, with the labels that each got.

#246 logging enhancement
  cmd/app/commandline.go
  go.mod
  go.sum
  internal/controller/etcdcluster_controller.go
  internal/log/handler.go
  internal/log/logger.go
  internal/log/option.go
  internal/log/stacktrace.go
Labels: enhancement, controllers

#245 Prepare release v0.3.0
  site/content/en/docs/v0.3/_index.md
  site/content/en/docs/v0.3/contribution-guidelines/_index.md
  site/content/en/docs/v0.3/examples/_index.md
  site/content/en/docs/v0.3/getting-started/_index.md
  site/content/en/docs/v0.3/overview/_index.md
  site/content/en/docs/v0.3/reference/_index.md
  site/content/en/docs/v0.3/reference/api.md
  site/hugo.yaml
Labels: documentation

#249 fix: sort etcd args to make them deterministic
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
Labels: bugfix, controllers

#250 Set extraArgs in the end of args processing
  internal/controller/factory/statefulset.go
  internal/controller/factory/statefulset_test.go
Labels: ok-to-test, controllers

#253 Remove custom code for managing conditions.
  config/rbac/role.yaml
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/condition.go
  internal/controller/factory/condition_test.go
  internal/controller/factory/configmap.go
  internal/controller/factory/configmap_test.go
Labels: chore, controllers

#254 Add resizing operation
  api/v1alpha1/etcdcluster_webhook.go
  api/v1alpha1/etcdcluster_webhook_test.go
  charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
  config/rbac/role.yaml
  examples/manifests/etcdcluster-persistent.yaml
  go.mod
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/pvc.go
  internal/controller/factory/pvc_test.go
  test/e2e/e2e_test.go
Labels: controllers, api-change

#255 Prepare release v0.4
  site/content/en/docs/v0.4/_index.md
  site/content/en/docs/v0.4/contribution-guidelines/_index.md
  site/content/en/docs/v0.4/examples/_index.md
  site/content/en/docs/v0.4/getting-started/_index.md
  site/content/en/docs/v0.4/overview/_index.md
  site/content/en/docs/v0.4/reference/_index.md
  site/content/en/docs/v0.4/reference/api.md
  site/hugo.yaml
Labels: documentation

#256 add "yq" as a dependency to "generate-docs" in Makefile
  Makefile
  site/content/en/docs/v0.4/reference/api.md
Labels: documentation, bugfix
