Repository aenix-io/etcd-operator, pull requests merged in 2025-04, with the labels that each got.

#284 feature/add-vpa
  charts/etcd-operator/README.md
  charts/etcd-operator/templates/workload/deployment.yml
  charts/etcd-operator/templates/workload/vpa.yml
  charts/etcd-operator/values.schema.json
  charts/etcd-operator/values.yaml
Labels: documentation, ok-to-test, feature

#286 Create TLS-capable clients if security enabled
  internal/controller/factory/etcd_client.go
Labels: controllers

#285 Bugs: wrong address and memory leak
  internal/controller/etcdcluster_controller.go
  internal/controller/factory/etcd_client.go
Labels: bugfix, controllers

#287 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: documentation

#280 add option to trigger release-assets workflow manually
  .github/workflows/release-assets.yaml
Labels: chore
